baseURL = "http://sidewalk.consulting"
languageCode = "en-us"
title = "Sidewalk Consulting"

theme = "coder"
languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentcodefences = true
pygmentscodefencessyntax = true

[params]
  author = "Sidewalk Consulting"
  info = "Almost anything is possible with code"
  description = "Sidewalk Consulting - almost anything is possible with code"
  keywords = "consulting,programming,solidity"

  hideCredits = false
  hideCopyright = false

  custom_css = []

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"

[taxonomies]
  tag = "tags"
  category = "categories"
